[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
clients = { version = "0.1.0", path = "../clients" }
env-vars = { version = "0.1.0", path = "../env_vars" }
inventory = "0.3.15"
