[package]
name = "spin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spinners = "4.1.0"
strum = { version = "0.24.0", features = ["derive"] }
